[package]
name = "polymodel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
convert_case = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_yaml = "0.9.34"

[dev-dependencies]
insta = "1.43.1"
